### PR TITLE
lex-cli: Prevent dashes in NSID from breaking compilation

### PR DESCRIPTION
**Pull request by spearcat**
Domain names can have dashes but lex-cli doesn't handle them and will emit invalid TypeScript.

### CODE REVIEW

**Comment by spearcat** [comment]
This also technically allows punycode NSIDs. Do with that information what you will.

**Comment by mary-ext** [comment]
I'll take a look tomorrow.

**Comment by spearcat** [comment]
image

**Comment by mary-ext** [comment]
publishing tomorrow it's 11:28pm

**Pull request merged**
